FROM ruby:3.1.2

RUN apt-get update -qq && \
    apt-get install -y --fix-missing curl gnupg2 && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y --fix-missing nodejs postgresql-client

RUN npm install -g yarn
WORKDIR /app

RUN gem install rails -v 7.0.0

COPY Gemfile Gemfile.lock ./

RUN bundle install || true

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]