version: '3.8'
services:
  db_user_service:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_development
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db_user_service
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  postgres-user-data:
  bundle: